
FROM node:latest
ARG registry=https://registry.npmjs.org/
LABEL Name=angular-pwa-seed Version=0.1.0
RUN mkdir -p /usr/src/app
COPY package.json /usr/src/app/package.json
COPY config.xml /usr/src/app/config.xml
RUN npm config set registry ${registry}
RUN yarn config set registry ${registry}
RUN npm install -g --unsafe-perm @angular/cli cordova@6.5.0 ionic@latest typescript sleep-ms concurrently mkdirp
RUN cd /usr/src/app && yarn install
WORKDIR /usr/src/app
COPY . /usr/src/app
EXPOSE 5555
# CMD npm run start


# TO RUN
# docker run -p 5555:5555 --name angular-pwa-seed-container --rm -i -t angular-pwa-seed bash
